### ISSUE TITLE
Cannot get more than 50 items while calling *.list methods

### ISSUE THREAD

**Issue by sbatov** [yarbshk/bitrix24-python3-client#12]
Colleagues, kindly advise how to implement reading all items from Bitrix *.list methods. I am stuck.
Code is the following:
...
resdict = bx24.call_webhook('xxxxxxxxxxxxxxx', 
            "crm.activity.list", 
            { 
				'order':{"ID": "DESC" },
				'filter':{"OWNER_TYPE_ID": 1,'PROVIDER_ID': 'CRM_WEBFORM'}, 
				'select':[ "ID", "SUBJECT" ],
				# 'more': True, - these are my attempts, which obviously failed
				# 'next': 100
			}
		) 

The code produces the dictionary with the following params: ... 'next': 50, 'total': 450 ...

**Comment by yarbshk** [comment]
hi @sbatov ! according to the [documentation](https://training.bitrix24.com/rest_help/general/lists.php):

> Because the number of elements, returned by REST-methods, depends on the specific conditions and parameters, Bitrix24 returns elements via "batches" of several elements (presently, not more than 50 elements in a batch)

you should make a sequence of requests in a loop and pass `start` option for each request to get all activities like follows:

```python
start = 0
crm_activities = []
while True:
    data = bx24.call_webhook('xxxxxxxxxxxxxxx', 'crm.activity.list', {'start': start, ...})
    crm_activities.append(data['result'])
    start += len(data['result'])
print(crm_activities)
```

the code snippet above wasn't tested because i haven't an account with a lot of data but i hope you have a point ;)

**Comment by sbatov** [comment]
Yep, i've got the point. Thank you!
