### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by noors312** [yarbshk/bitrix24-python3-client#2]
Need to add authorize function, without browser

**Comment by yarbshk** [comment]
Hi @NursErgesh, you could implement that functionality by yourself. It's not a case of the library.

As far as I know, **Bitrix24 haven't API to login users**, therefore, you need to be logged into your Bitrix24 account within a browser to successfully request the authorize endpoint in another case you'll be redirected to the login page. So if you request the authorize endpoint programmatically:

```python
import requests
requests.get('https://b24-yxnpd2.bitrix24.ua/oauth/authorize/?client_id=local.5bdc56a0090df2.18210824&response_type=code')
```

...it'll return an HTML document (login page) because your user session doesn't exist.

There are a couple of **solutions**:

- [make it semiautomatically](https://gist.github.com/yarbshk/ebbdccd7b9c1abd2ba32fb5518578b7e) by opening browser window and sending an authentication request while using your application;
- simulate browser environment by using tools like [Selenium](https://www.seleniumhq.org/) (I'm not sure if it'll be working with Bitrix24 but I give you a point).

Hope it helps :)

P.S. Close the issue and mark it as irrelevant one.

**Comment by noors312** [comment]
Thank you for answer. I found the solution in webhooks, you can send GET or POST request with params to hook_url/rest_method, and that's it... no authentication
